### ISSUE TITLE
已经存在redisco项目

### ISSUE THREAD

**Issue by ayanamist** [huangzworks/ooredis#3]
建议楼主放弃本项目，去当redisco项目的contribute

**Comment by huangzworks** [comment]
是的，OORedis刚开始的想法就是来源于redisco的container模块，我的确考虑过fork一个redisco，但是后来的一些想法让我放弃了redisco转而开始写OORedis：
1. redisco是一个mapper，而OORedis的目标则是做一个Pythonic风格的redis库（也即是一个更好的redis-py）而不是一个mapper，它们的功用不同。
2. 那为什么不修改redisco的container呢？因为container是作为redisco这个Mapper的后端使用的，对Mapper的改动可能会影响到redisco本身，而OORedis是单独一个项目，可以不拘泥于其他代码独立演进。

以上两个就是主要原因，当然也有一些像是“再造一个车轮，写一个redis库学习一下“，”我害怕接手别人的代码“这类私人理由，诸如此类，所以我就选择了写OORedis而不是redisco。

：）

**Comment by honglei** [comment]
建议：
1，现在的代码只能使用本机的redis， 如下代码无法使用

import ooredis
r = ooredis.connect(host='211.69.*', port=6379, db=0)  
prj = ooredis.Dict('ooredis')
prj['name'] = 'ooredis'

**Comment by huangzworks** [comment]
@honglei 我测试了一下，的确如此，是个BUG，我现在去修复。

**Comment by huangzworks** [comment]
OK，修复完毕。
