### ISSUE TITLE
关于 OORedis 2.0 版本

### ISSUE THREAD

**Issue by huangzworks** [huangzworks/ooredis#4]
随着 Redis 2.4 版本的功能基本稳定，我想现在开始对 OORedis 进行更新是一个不错的时机，因为打算修改的地方比较多，因此我将这个版本命名为 OORedis 2.0 。

OORedis 2.0 要做的事情有如下：
- 补全 ABC mixin 中各个 special method 的文档，并生成 API 手册。
- 编写一个 OORedis 的教程（tutorial）。
- 利用 Redis 2.4 版本几个新命令的新特性（一次操作多个元素），提升诸如 Set 类的 &= 、 |= 、^= 等操作的速度
- 对现有代码进行 formatting 工作
- 移除 Server 模块：因为我觉得OORedis 应该专注于对数据结构进行操作上，Server、Connect等命令的实现交给 redis-py 去做
- List 的实现和 API 都要进行大修改，SortedSet的实现估计也要进行更改
- 丰富功能：补全之前一些因为比较复杂而没有实现的功能，比如 List 类的 del[start:end] 操作
- 对测试进行重构，引入 nosetest 

嗯，要做的大概就是这些，如果对以上计划有疑问或者对新版本有更好的建议，欢迎留言。

**Comment by huangzworks** [comment]
因为 OORedis 2.0 里面有些地方要用到 scripting ，但是 redis-py 的脚本支持还没加上，所以目前还得等 redis-py 的脚本支持赶上来，更新才能继续。

**Comment by honglei** [comment]
请教个问题： Transactions在OORedis里面能否实现？就是https://github.com/andymccurdy/redis-py/的Pipelines功能
   比如我想利用SortSet来做成一个循环队列，每次把首元素放到放置到队列的尾端。既要保证不重复，又能够动态的增删元素。

   redisco的代码如下：
   s = SortSet("xx")
   s.incr_by(s[0], s.score(s[-1]) +1 - s.score(s[0]) )  #此处会有多次读写操作，必须保证在一个Traction内完成

**Comment by huangzworks** [comment]
@honglei 

不好意思， OORedis 目前还不支持 pipeline 功能。

OORedis 一直关注的都是那种能够在一次存取之内搞定的简单操作，没有考虑太复杂的模式。

**Comment by honglei** [comment]
谢谢，我尝试用redis_py的pipeline实现：

```
import redis
r = redis.StrictRedis(host=REDIS_IP, port=6379, db=0)
    print r.zrange('checkd',0,-1)
r.zadd("checkd" ,1,'d')
r.zadd("checkd" ,2,'b')
r.zadd("checkd" ,3,'c')
r.zadd("checkd" ,5,'f')  
pipe = r.pipeline()
first = pipe.zrange('checkd',0,0)[0]
last = pipe.zrange('checkd',-1,-1)[0]
first_score = pipe.zscore('checkd',first)
length = pipe.zcard('checkd') # 
pipe.zincrby( 'checkd', first, first_score+ length ) #TypeError:

pipe.execute()
print r.zrange('checkd',0,-1)
```

但是会有如下错误: 
 #TypeError： unsupported operand type(s) for +: 'StrictPipeline' and 'StrictPipeline'
 不太清楚如何解决。

**Comment by huangzworks** [comment]
@honglei 

你描述的模式单纯用 pepiline 是解决不了的，这个模式涉及服务器和客户端之间的多次访问，必须使用事务来执行: http://redis.io/topics/transactions

另一种更方便的方法是，使用 Redis 2.6 版本的脚本功能。

以下两个链接是脚本功能的介绍，其中第一个链接的案例和你的模式很相似，可能对你有帮助：

http://huangz.me/redis-scripting-short-guide/

http://redis.readthedocs.org/en/latest/script/eval.html

**Comment by honglei** [comment]
@huangz1990 
 谢谢，原来redis 2.6 的脚本是要用Lua来写。

**Comment by huangzworks** [comment]
@honglei 不客气。
